name = "haejo"
compatibility_date = "2024-11-01"

# React Pages 빌드 결과 위치
pages_build_output_dir = "build"

# D1 데이터베이스 연결
[[d1_databases]]
binding = "DB"
database_name = "travel-planner-db"
database_id = "b549fbee-3a7c-44e8-b726-4086beb25576"

