# wrangler.toml
name = 'haejo'
compatibility_date = "2024-11-01"

[pages]
project_name = "travel-planner"
build_output_dir = "build"

[[d1_databases]]
binding = "DB"
database_name = "travel-planner-db"
database_id = "b549fbee-3a7c-44e8-b726-4086beb25576"
