name = "haejo"
compatibility_date = "2024-11-01"

# React Pages 빌드 결과 위치
pages_build_output_dir = "build"

# D1 데이터베이스 연결
[[d1_databases]]
binding = "DB"
database_name = "travel-planner-db"
database_id = "b5acdfab-4fff-4600-8434-d4ae3256cb0c"

